@url= http://localhost:3003


### user login
POST {{url}}/login
content-type: application/json

{
    "login": "kc",
    "password": "ppp"
}


### user signup
POST {{url}}/signup
content-type: application/json

{
    "firstName": "Giacomo",
    "lastName": "Tolari",
    "login": "gc",
    "email": "gc@gmail.com",
    "password1": "nnn",
    "password2": "nnn",
    "accessGroups": "loggedInUsers, notYetApprovedUsers",
}


### show user data
GET {{url}}/user
content-type: application/json

### user logout
GET {{url}}/logout
content-type: application/json

